### ISSUE TITLE
Complete a quest - become a rockstar!

### ISSUE THREAD

**Issue by nruffilo** [nruffilo/YouTodoProj#5]
When a quest is completed, we need to make the user feel like a rockstar.  The "rewards" needs to be displayed to the user, as well as XP given based off the size of the task.
1: 10 XP
2: 50 XP
3: 200 XP
4: 500 XP

Fanfare, fireworks, a modal that says: "Job well done, adventurer." etc.  Go ham, reward the heck out of the user for completing their chore.  Bonus points if it's random, and if we can have more visual rewards for harder tasks.

**Comment by mariel-delagarza** [comment]
Dropping these fireworks ideas here before I forget they exist: 
* [CSS Script](https://www.cssscript.com/firework-animation-canvas/)
* [CodePen](https://codepen.io/whqet/pen/Auzch)
* [Vanilla JS Example](https://slicker.me/javascript/fireworks.htm)

**Comment by nruffilo** [comment]
Sweet!  Thanks!  Yes, tons of things like this.  Ideally it would be customizable based off the theme.  If you're pirate theme, then a chest with gold could open up.  If you're space themed or sci-fi, then a ship launching...  Who knows, but I want you to feel awesome when you complete a quest.
